### ISSUE TITLE
Baaijte.Optimizely.ImageSharp.Web.Providers.BlobImageProvider.GetAsync could not load

### ISSUE THREAD

**Issue by chaudhry13** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#28]
I am getting this exception 

System.IO.FileNotFoundException: Could not load file or assembly 'EPiServer, Version=12.21.4.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'. The system cannot find the file specified.
File name: 'EPiServer, Version=12.21.4.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'
   at Baaijte.Optimizely.ImageSharp.Web.Providers.BlobImageProvider.GetAsync(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

I have the following versions

```
<PackageReference Include="Baaijte.Optimizely.ImageSharp.Web" Version="3.0.1" />
<PackageReference Include="PictureRenderer" Version="3.12.0" />
<PackageReference Include="PictureRenderer.Optimizely" Version="3.2.0" />
<PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
<PackageReference Include="SixLabors.ImageSharp.Web" Version="3.1.3" />
<PackageReference Include="SixLabors.ImageSharp.Web.Providers.Azure" Version="3.1.3" />
```

Am I missing something?

**Comment by vnbaaij** [comment]
Please seek help in the Optimizely forum. It seems not to be an issue with the library but rather with your configuration. Otherwise there would be more reports.

I am not working for or with Optimizely anymore. This package is in maintenance mode.
