### ISSUE TITLE
Not working latest Epi (12.4.2)

### ISSUE THREAD

**Issue by Dandroid5000** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#8]
Hi, 
I have just updated the Epi packages (EPiServer.CMS.Core -> 12.4.2 and EPiServer.Framework -> 12.4.2) and am now getting the following exception when trying to render and resize an image.

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<SixLabors.ImageSharp.Formats.IImageFormat> SixLabors.ImageSharp.Image.DetectFormatAsync(SixLabors.ImageSharp.Configuration, System.IO.Stream)'.
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary`2 commands)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary`2 commands)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Please let me know if there is anything I might be doing wrong or if you need any more info.
Cheers
Dan

**Comment by Dandroid5000** [comment]
Further, just pionting out that EPiServer.CMS.Core 12.4.2 updates the dependeny on SixLabors.ImageSharp (>= 1.0.4 && < 2.0.0) to (>= 2.0.0 && < 3.0.0)

**Comment by vnbaaij** [comment]
It looks like ImageSharp 2.0 (which is dependency of 12.4.2) does not work with ImageSharp.Web 1.0.5 (latest released version) If this is confirmed (I've asked ImageSharp author), we will need to wait until ImageSharp.Web 2.0 is released.
I've made preparations for this in the v2 branch. As indicated by the number, this will be a next major version targeting .NET 6.

**Comment by Dandroid5000** [comment]
Ok, thanks for confirming.
So there will be no fix targeting. NET 5? We have a number of other dependencies stuck in .NET 5, including some Episerver packages, so it would good to know.
Thanks again

**Comment by vnbaaij** [comment]
James confirmed ImageSharp 2.0 does not work with ImageSharp.Web 1.5. 
Targeting both .NET 5 and .NET 6 will be hard, I think (because of the changes they made with 12.4.2). Besides that, .NET 5 is out of support in less than 2 months (May 8th). I feel like everyone else should step up (including Optimizely) instead of me backporting stuff...

**Comment by DrewNull** [comment]
Hey peeps, I created a bug report on World here: 
https://world.optimizely.com/forum/developer-forum/Problems-and-bugs/Thread-Container/2022/4/episerver-cms-core-12-4-2-breaks-imagesharp/

Hopefully we can get some traction. Vincent thank you for putting this package together and trying to get it to work!

**Comment by Rrydh** [comment]
SixLabors just released v2.0.0 of ImageSharp.Web

**Comment by vnbaaij** [comment]
Version 2.0.0 has just been uploaded to Optimizely. Should be available soon

**Comment by evest** [comment]
v2 is now on the feed.

**Comment by vnbaaij** [comment]
Thanks Steve! All is well, I hope?
